### ISSUE TITLE
List of themes not loading

### ISSUE THREAD

**Issue by ljcool2006** [replugged-org/replugged-web-rewrite#1]
All it does is send requests to 127.0.0.1.

**Comment by lexisother** [comment]
Please elaborate.

**Comment by ljcool2006** [comment]
1. Go to https://replugged.dev/store/themes
2. Check the network console
3. Look at requests sending to 127.0.0.1

**Comment by lexisother** [comment]
It's supposed to do that. The website establishes a connection with your running Discord client (where Replugged is installed) over a WebSocket. (see the request status of [`101`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/101)).

It then fetches the list of installed addons so it can show an "Installed" text on the button in the cards.
<img width="864" alt="image" src="https://github.com/replugged-org/replugged-web-rewrite/assets/54973868/e2694e14-d0a4-43d2-b594-56cd85af7aa4">
<img width="330" alt="image" src="https://github.com/replugged-org/replugged-web-rewrite/assets/54973868/26c42ca8-6127-40f5-9980-4dfbcaf700cc">

Closing as non-issue.
